//src/Home.js
import React from 'react';import { Text, View, StyleSheet, ImageBackground, TouchableOpacity } from 'react-native';
//Home Pageconst Home = ({ navigation }) => { return( <View style={styles.container}> <ImageBackground style={styles.bgImage} source={require('../assets/cityguide-bg-image-4.jpg')}> <Text style={styles.headerText}>Cityguide</Text> <Text style={styles.tagline}>Explore the best places of the world's most vibrant cities!</Text> <TouchableOpacity style={styles.loginButton} onPress={() => navigation.navigate('Login')}> <Text style={styles.loginButtonText}>Login</Text> </TouchableOpacity>
 <TouchableOpacity style={styles.registerButton}> <Text style={styles.registerButtonText}>Register</Text> </TouchableOpacity>
 </ImageBackground > </View> )}
 //Styling Home Pageconst styles = StyleSheet.create({ container: { flex: 1 }, bgImage: { flex: 1, alignItems: 'center' }, headerText: { marginTop:200, fontSize:70, color: '#FFFFFF', fontFamily: 'cursive', fontWeight: "bold" }, tagline: { marginTop: 90, color: '#FFFFFF', fontSize:18, marginLeft: 30, textAlign: 'center' }, loginButton: { marginTop: 90, height: 50, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: 20, width: 310, borderRadius: 5, backgroundColor: "#FFFFFF", }, registerButton: { marginTop: 3, height: 50, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginBottom: 20, width: 310, borderRadius: 5, backgroundColor: 'transparent', borderWidth: 1, borderColor: '#FFFFFF' }, loginButtonText: { color: '#1E90FF', fontSize: 18, }, registerButtonText: { color: '#FFFFFF', fontSize: 18, },});
export default Home;

//src/Login.js
import React from "react";import { Text, View, StyleSheet, Image, TextInput, TouchableOpacity } from "react-native";
//Login Pageconst Login = ({ navigation }) => { return ( <View style={styles.container}> <View style={styles.header}> <Image style={styles.image} source={require('../assets/cityguide-bg-image-4.jpg')} /> <Text style={styles.headerText}>Cityguide</Text> </View>
 <View style={styles.bodyContent}> <Text style={styles.welcomeText}>Welcome back!</Text>
 <TextInput style={styles.inputField} placeholderTextColor="#C8C8C8" placeholder="📨 Your email address"></TextInput> <TextInput style={styles.inputField} placeholderTextColor="#C8C8C8" placeholder="🔓︎ Your password"></TextInput>
 <TouchableOpacity style={styles.loginButton} onPress={() => navigation.navigate('BrowseCategories')}> <Text style={styles.loginButtonText}>Login</Text> </TouchableOpacity>
 <TouchableOpacity style={styles.facebookButton} onPress={() => navigation.navigate('')}> <Text style={styles.registerButtonText}>Facebook</Text> </TouchableOpacity>
 <TouchableOpacity onPress={() => navigation.navigate('')}> <Text style={styles.forgotPassword}>Forgot password?</Text> </TouchableOpacity>
 </View> </View> )}
//Styling Login Pageconst styles = StyleSheet.create({ container: { flex: 1 }, header: { height: 220, alignItems: 'center' }, image: { height: 220, width: '100 %', position: 'absolute' }, headerText: { marginTop: 70, fontSize: 80, color: '#FFFFFF', fontFamily: 'cursive', }, bodyContent: { alignItems: 'center' }, welcomeText: { fontSize: 34, marginTop: 30, color: '#1E90FF', marginBottom: 40, }, inputField: { width: '85%', height: 45, marginTop: 6, marginBottom: 25, borderBottomWidth: 1, borderColor: '#C8C8C8' }, loginButton: { marginTop: 18, height: 50, justifyContent: 'center', alignItems: 'center', marginBottom: 18, width: '85%', borderRadius: 5, borderWidth: 1, borderColor: '#1E90FF', backgroundColor: 'transparent', }, facebookButton: { marginTop: 3, height: 50, justifyContent: 'center', alignItems: 'center', width: '85%', borderRadius: 5, backgroundColor: '#1E90FF', }, loginButtonText: { color: '#1E90FF', fontSize: 16, }, registerButtonText: { color: '#FFFFFF', fontSize: 16, }, forgotPassword: { color: '#A9A9A9', marginTop: 15 }});
export default Login;


//Header.js
import React, { useState } from "react";import { Text, View, StyleSheet, Image, TouchableOpacity, TextInput } from "react-native";
//Header Pageconst Header = (props) => {
 const [searchTerm, setSearchTerm] = useState(""); //const [restaurantList, setRestaurantList] = useState(props.restaurantList); //const [restaurantName, setRestaurantName] = useState(props.restaurantName);
 return ( <View style={styles.header}> <View style={{ width: "15%" }}> <TouchableOpacity onPress={() => props.navigationProp.navigate(props.navigationRoute)}> <Image style={styles.leftArrowIcon} source={require('../assets/left-arrow-icon.png')} /> </TouchableOpacity> </View> <View style={{ width: "60%" }}> <Text style={styles.headerText}>{props.heading}</Text> </View>
 <View style={{ marginTop: 8, flexDirection: "row", width: "30%", height: "70%", backgroundColor: "transparent", alignItems: "center", justifyContent: "center" }}> <Image style={styles.searchIcon} source={require('../assets/Search_Icon.png')} /> <TextInput style={{ color: "black" }} placeholder="Search" placeholderTextColor="#ffffff" value={searchTerm} onChangeText={(text) => { setSearchTerm(text) }} > </TextInput> </View>
 {/* <View> {props.restaurantList.filter((val) => { if (searchTerm === "") { return val } else if (props.restaurantName.toLowerCase().includes(searchTerm.toLowerCase())) { return val } }).map((val, key) => { return ( <View key={key} > <Text> {val.restaurantName} </Text> </View> ) })} </View> */}
 {/* <View style={{ width: "10%" }}> <TouchableOpacity> <Image style={styles.searchIcon} source={require('../assets/Search_Icon.png')} /> </TouchableOpacity> </View> */} </View> )}
//Styling Header Pageconst styles = StyleSheet.create({ header: { height: 90, width: "100%", backgroundColor: '#1E90FF', flexDirection: "row", alignItems: "center", padding: 20 }, headerText: { color: '#FFFFFF', fontSize: 18, textAlign: "center", textTransform: "capitalize" }, leftArrowIcon: { height: 18, width: 25, }, searchIcon: { // height: "40%", // width: "6%", height: 15, width: 20, padding: 3 }, // searchText: { // height: 20, // width: "80%", // height: 18, // width: 25, // flex: 1, // color: "black", // backgroundColor: "#FFFFFF" // },});
export default Header;



//Header 2
// import React, { useState } from "react";// import { Text, View, StyleSheet, Image, TouchableOpacity, TextInput } from "react-native";
// //Header Page// const Header = (props) => {
// const [searchTerm, setSearchTerm] = useState("");// //const [restaurantList, setRestaurantList] = useState(props.restaurantList);// //const [restaurantName, setRestaurantName] = useState(props.restaurantName);
// return (// <View style={styles.header}>// <View style={{ width: "15%" }}>// <TouchableOpacity onPress={() => props.navigationProp.navigate(props.navigationRoute)}>// <Image style={styles.leftArrowIcon} source={require('../assets/left-arrow-icon.png')} />// </TouchableOpacity>// </View>// <View style={{ width: "60%" }}>// <Text style={styles.headerText}>{props.heading}</Text>// </View>
// <View style={{ marginTop: 8, flexDirection: "row", width: "30%", height: "70%", backgroundColor: "transparent", alignItems: "center", justifyContent: "center" }}>// <Image style={styles.searchIcon} source={require('../assets/Search_Icon.png')} />// <TextInput style={{ color: "black" }} placeholder="Search" placeholderTextColor="#ffffff" value={searchTerm} onChangeText={(text) => {// setSearchTerm(text)// }} >// </TextInput>// </View>
// {/* <View>// {props.restaurantList.filter((val) => {// if (searchTerm === "") {// return val// }// else if (props.restaurantName.toLowerCase().includes(searchTerm.toLowerCase())) {// return val// }// }).map((val, key) => {// return (// <View key={key} >// <Text>// {val.restaurantName}// </Text>// </View>// )// })}// </View> */}
// {/* <View style={{ width: "10%" }}>// <TouchableOpacity>// <Image style={styles.searchIcon} source={require('../assets/Search_Icon.png')} />// </TouchableOpacity>// </View> */}// </View>// )// }
// //Styling Header Page// const styles = StyleSheet.create({// header: {// height: 90,// width: "100%",// backgroundColor: '#1E90FF',// flexDirection: "row",// alignItems: "center",// padding: 20// },// headerText: {// color: '#FFFFFF',// fontSize: 18,// textAlign: "center",// textTransform: "capitalize"// },// leftArrowIcon: {// height: 18,// width: 25,// },// searchIcon: {// // height: "40%",// // width: "6%",// height: 15,// width: 20,// padding: 3// },// // searchText: {// // height: 20,// // width: "80%",// // height: 18,// // width: 25,// // flex: 1,// // color: "black",// // backgroundColor: "#FFFFFF" // // },// });
// export default Header;


// import React from "react";// import { Text, View, StyleSheet, Image, TouchableOpacity } from "react-native";
// //Header Page// const Header = (props) => {// return (// <View style={styles.header}>// <View style={{ width: "10%" }}>// <TouchableOpacity>// <Image style={styles.leftArrowIcon} source={require('../assets/left-arrow-icon.png')}/>// </TouchableOpacity>// </View>// <View style={{ width: "80%" }}>// <Text style={styles.headerText}>Browse {props.heading}</Text>// </View>// <View style={{ width: "10%" }}>// <TouchableOpacity>// <Image style={styles.searchIcon} source={require('../assets/Search_Icon.png')} />// </TouchableOpacity>// </View>// </View>// )// }
// //Styling Header Page// const styles = StyleSheet.create({// header: {// height: 90,// width: "100%",// backgroundColor: '#1E90FF',// flexDirection: "row",// alignItems: "center",// padding: 20// },// headerText: {// color: '#FFFFFF',// fontSize: 18,// textAlign: "center",// textTransform: "capitalize"// },// leftArrowIcon: {// height: 18,// width: 25,// },// searchIcon: {// // height: "40%",// // width: "6%",// height: 18,// width: 25,// },// });
// export default Header;

//Footer.js
import React from "react";import { Text, View, StyleSheet, Image, TouchableOpacity } from "react-native";
//Footer Pageconst Footer = ({props}) => { // alert(JSON.stringify(props)); return ( <View style={styles.footer} > <View style={styles.seperateFoooterTab}> <TouchableOpacity> <Image style={styles.footerIcon} source={require('../assets/world-icon.jpeg')}></Image> <Text style={styles.footerTabText}>Location</Text> </TouchableOpacity> </View>
 <View style={styles.seperateFoooterTab}> <TouchableOpacity onPress={() => props.navigate('BrowseCategories') }> <Image style={styles.footerIcon} source={require('../assets/hamburger-menu-icon.png')}></Image> <Text style={styles.footerTabText}>Browse</Text> </TouchableOpacity> </View>
 <View style={styles.seperateFoooterTab}> <TouchableOpacity> <Image style={styles.footerIcon} source={require('../assets/heart.jpeg')}></Image> <Text style={styles.footerTabText}>Favorites</Text> </TouchableOpacity> </View>
 <View style={styles.seperateFoooterTab}> <TouchableOpacity> <Image style={styles.footerIcon} source={require('../assets/profile-icon.png')}></Image> <Text style={styles.footerTabText}>Profile</Text> </TouchableOpacity> </View> </View> )}
//Styling Footer Pageconst styles = StyleSheet.create({ footer: { height: 80, backgroundColor: '#FBFCFC', flexDirection: "row", paddingHorizontal: 25, paddingVertical: 20 }, footerIcon: { height: 30, width: 30, }, seperateFoooterTab: { width: "25%", flexDirection: "column", opacity: 0.5, justifyContent: "center", alignItems: "center" }, footerTabText: { color: '#585858', }});
export default Footer;

//BrowseRestaurants.js
import React, { useEffect, useState } from "react";import { Text, View, StyleSheet, Image, ScrollView, TouchableOpacity, TextInput } from "react-native";import Footer from "./Footer";//import Header from "./Header";import Axios from 'axios';
//Browse Restaurant Pageconst BrowseRestaurants = ({ navigation }) => {
 const [restaurant, setRestaurant] = useState([]); const category = navigation.getParam('categoryName'); const [searchTerm, setSearchTerm] = useState("");

 useEffect(() => { Axios.get(`https://damp-sea-94376.herokuapp.com/api/getFoodNearBy/lat=22.69483315&long=75.8539546170826&radius=1500&nextPage=false&types=${category}`) .then(function (response) { //alert(category); setRestaurant(response.data.result); }) .catch(function (error) { alert(error.message); }) }, []);
 // function filterRestaurant() { // <View> // {restaurant.filter((val) => { // if (searchTerm === "") { // return val // } // else if (item.name.toLowerCase().includes(searchTerm.toLowerCase())) { // return val // } // }) // // .map((val, key) => { // // return ( // // <View key={key} > // // <Text> // // {val.restaurantName} // // </Text> // // </View> // // ) // // }) // } // </View> // }
 function _handleSearch(text) { setSearchTerm(text) // setRestaurant([]); // { // restaurant.filter((val) => { // if (searchTerm === "") { // return val // } // else if (val.name.toLowerCase().includes(searchTerm.toLowerCase())) { // return val // } // }) // }
 let filterArr= restaurant.filter((item,i)=>item.name.toLowerCase()===searchTerm.toLowerCase()) console.log('filterArr',filterArr,searchTerm) setRestaurant(filterArr); }


 return ( <View style={styles.container}> {/* <Header heading={category} navigationProp={navigation} navigationRoute={'BrowseCategories'} restaurantList={restaurant} restaurantName={item.name} /> */}

 <View style={styles.header}> <View style={{ width: "15%" }}> <TouchableOpacity onPress={() => navigation.navigate('')}> <Image style={styles.leftArrowIcon} source={require('../assets/left-arrow-icon.png')} /> </TouchableOpacity> </View> <View style={{ width: "60%" }}> <Text style={styles.headerText}>Restaurant</Text> </View>
 <View style={{ marginTop: 8, flexDirection: "row", width: "30%", height: "70%", backgroundColor: "transparent", alignItems: "center", justifyContent: "center" }}> <Image style={styles.searchIcon} source={require('../assets/Search_Icon.png')} /> <TextInput style={{ color: "black" }} placeholder="Search" placeholderTextColor="#ffffff" value={searchTerm}
 onChangeText={_handleSearch} >
 </TextInput> </View> </View>
 <ScrollView> {restaurant.map((item) => { return ( <View> <TouchableOpacity> <View style={styles.restaurantRowStyle}>
 <View style={{ width: "20%" }}> <Image style={styles.restaurantImage} source={{ uri: item.image }} /> </View>
 <View style={{ width: "50%", marginTop: 5, flex: 1 }}> <Text style={styles.restaurantText}>{item.name}</Text> <View style={{ flexDirection: "column" }}> <View style={{ flexDirection: "row", marginLeft: 5, marginTop: 5 }}> <Image style={styles.gpsIcon} source={require('../assets/location.jpg')} /> <Text style={styles.locationText}>{item.address}</Text> <Image style={styles.starIcon} source={require('../assets/rating-star.png')} ></Image> <Text style={styles.liketext}>{item.rating}</Text> </View> </View> </View>
 <View style={{ width: "20%", paddingLeft: 5, paddingRight: 5 }}> <Image style={styles.rightArrow} source={require('../assets/right-arrow.jpeg')}></Image> </View>
 </View> </TouchableOpacity>
 <View style={{ borderBottomColor: '#A9A9A9', borderBottomWidth: 0.4, marginTop: 5 }} /> </View> ) } )} </ScrollView> <Footer props={navigation} /> </View> )}
//Styling Browse Restaurant Dataconst styles = StyleSheet.create({ container: { flex: 1 }, restaurantRowStyle: { flex: 1, flexDirection: "row", padding: 20, height: "10%" }, restaurantHeading: { flexDirection: "row" }, restaurantImage: { height: "130%", width: "100%", borderRadius: 5 }, restaurantText: { marginLeft: 10, fontSize: 14 }, rightArrow: { height: 12, width: 12, marginTop: 15, marginLeft: 50 }, gpsIcon: { height: 15, width: 15, }, locationText: { color: '#A9A9A9', fontSize: 10 }, starIcon: { height: 18, width: 18, marginLeft: 5 }, liketext: { color: '#A9A9A9' },
 //header styling header: { height: 90, width: "100%", backgroundColor: '#1E90FF', flexDirection: "row", alignItems: "center", padding: 20 }, headerText: { color: '#FFFFFF', fontSize: 18, textAlign: "center", textTransform: "capitalize" }, leftArrowIcon: { height: 18, width: 25, }, searchIcon: { // height: "40%", // width: "6%", height: 15, width: 20, padding: 3 },
});
export default BrowseRestaurants;
//**********************************************Browse Restaurant 2**************************************************************/
// import React, { useEffect, useState } from "react";// import { Text, View, StyleSheet, Image, ScrollView, TouchableOpacity } from "react-native";// import Footer from "./Footer";// import Header from "./Header";// import Axios from 'axios';
// //Browse Restaurant Page// const BrowseRestaurants = ({ navigation }) => {
// const [restaurant, setRestaurant] = useState([]);// const category = navigation.getParam('categoryName');
// useEffect(() => {// Axios.get(`https://damp-sea-94376.herokuapp.com/api/getFoodNearBy/lat=22.69483315&long=75.8539546170826&radius=1500&nextPage=false&types=${category}`)// .then(function (response) {// //alert(category);// setRestaurant(response.data.result);// })// .catch(function (error) {// alert(error.message);// })// }, []);
// return (// <View style={styles.container}>// <Header // heading={category}// navigationProp={navigation}// navigationRoute={'BrowseCategories'}// restaurantList={restaurant}// restaurantName={item.name} />// <ScrollView>// {restaurant.map((item) => {// return (// <View>// <TouchableOpacity>// <View style={styles.restaurantRowStyle}>
// <View style={{ width: "20%" }}>// <Image style={styles.restaurantImage} source={{uri:item.image}} />// </View>
// <View style={{ width: "50%", marginTop: 5, flex: 1 }}>// <Text style={styles.restaurantText}>{item.name}</Text>// <View style={{ flexDirection: "column" }}>// <View style={{ flexDirection: "row", marginLeft: 5, marginTop: 5 }}>// <Image style={styles.gpsIcon} source={require('../assets/location.jpg')} />// <Text style={styles.locationText}>{item.address}</Text>// <Image style={styles.starIcon} source={require('../assets/rating-star.png')} ></Image>// <Text style={styles.liketext}>{item.rating}</Text>// </View>// </View>// </View>
// <View style={{ width: "20%", paddingLeft: 5, paddingRight: 5 }}>// <Image style={styles.rightArrow} source={require('../assets/right-arrow.jpeg')}></Image>// </View>
// </View>// </TouchableOpacity>
// <View// style={{// borderBottomColor: '#A9A9A9',// borderBottomWidth: 0.4,// marginTop: 5// }}// />// </View>// )// }// )}// </ScrollView>// <Footer props={navigation} />// </View>// )// }
// //Styling Browse Restaurant Data// const styles = StyleSheet.create({// container: {// flex: 1// },// restaurantRowStyle: {// flex: 1,// flexDirection: "row",// padding: 20, height: "10%"// },// restaurantHeading: {// flexDirection: "row"// },// restaurantImage: {// height: "130%",// width: "100%",// borderRadius: 5// },// restaurantText: {// marginLeft: 10,// fontSize: 14// },// rightArrow: {// height: 12,// width: 12,// marginTop: 15,// marginLeft: 50// },// gpsIcon: {// height: 15,// width: 15,// },// locationText: {// color: '#A9A9A9',// fontSize: 10// },// starIcon: {// height: 18,// width: 18,// marginLeft: 5// },// liketext: {// color: '#A9A9A9'// }// });
// export default BrowseRestaurants;

//**********************************************Browse Restaurant 1**************************************************************/
// import React from "react";// import { Text, View, StyleSheet, Image, ScrollView, TouchableOpacity } from "react-native";// import Footer from "./Footer";// import Header from "./Header";
// //Restaurant Data Array// const datas = [// {// id: 1,// restaurantImageSource: require('../assets/pizza.jpg'),// restaurantName: "Gramercy Tavern",// gpsSource: require('../assets/location.jpg'),// locationName: "42 E 20th St",// heartIconSource: require('../assets/heart.jpeg'),// likesText: "228",// rightArrowSource: require('../assets/right-arrow.jpeg')// },// {// id: 2,// restaurantImageSource: require('../assets/burger.jpg'),// restaurantName: "Blue Hill",// gpsSource: require('../assets/location.jpg'),// locationName: "75 Washington PI",// heartIconSource: require('../assets/heart.jpeg'),// likesText: "215",// rightArrowSource: require('../assets/right-arrow.jpeg')// },// {// id: 3,// restaurantImageSource: require('../assets/pasta.png'),// restaurantName: "Le Bernardin",// gpsSource: require('../assets/location.jpg'),// locationName: "155 W 51st St",// heartIconSource: require('../assets/heart.jpeg'),// likesText: "199",// rightArrowSource: require('../assets/right-arrow.jpeg')// },// {// id: 4,// restaurantImageSource: require('../assets/french-fries.jpg'),// restaurantName: "Jean-Georges",// gpsSource: require('../assets/location.jpg'),// locationName: "1 Central Park West",// heartIconSource: require('../assets/heart.jpeg'),// likesText: "183",// rightArrowSource: require('../assets/right-arrow.jpeg')// },// {// id: 5,// restaurantImageSource: require('../assets/brownie.jpg'),// restaurantName: "The Four Seasons",// gpsSource: require('../assets/location.jpg'),// locationName: "99 E 52md St",// heartIconSource: require('../assets/heart.jpeg'),// likesText: "178",// rightArrowSource: require('../assets/right-arrow.jpeg')// },// {// id: 6,// restaurantImageSource: require('../assets/sandwich.jpeg'),// restaurantName: "Ninja New York",// gpsSource: require('../assets/location.jpg'),// locationName: "25 Hudson St",// heartIconSource: require('../assets/heart.jpeg'),// likesText: "78",// rightArrowSource: require('../assets/right-arrow.jpeg')// },// ];
// //Mapping Function for Restaurant Data// function createData(data) {// return (// <View>// <TouchableOpacity>// <View style={styles.restaurantRowStyle}>
// <View style={{ width: "20%" }}>// <Image style={styles.restaurantImage} source={data.restaurantImageSource} />// </View>
// <View style={{ width: "70%", marginTop: 5 }}>// <Text style={styles.restaurantText}>{data.restaurantName}</Text>// <View style={{ flexDirection: "column" }}>// <View style={{ flexDirection: "row", marginLeft: 5, marginTop: 5 }}>// <Image style={styles.gpsIcon} source={data.gpsSource} />// <Text style={styles.locationText}>{data.locationName}</Text>// <Image style={styles.heartIcon} source={data.heartIconSource} ></Image>// <Text style={styles.liketext}>{data.likesText}</Text>// </View>// </View>// </View>
// <View style={{ width: "10%" }}>// <Image style={styles.rightArrow} source={data.rightArrowSource}></Image>// </View>
// </View>// </TouchableOpacity>
// <View// style={{// borderBottomColor: '#A9A9A9',// borderBottomWidth: 0.4,// marginTop: 5// }}// />// </View>// )// }
// //Browse Restaurant Page// const BrowseRestaurants = ({ navigation }) => {
// return (// <View style={styles.container}>// <Header heading="Browse Restaurants" />// <ScrollView>// {datas.map(createData)}// </ScrollView>// <Footer props={navigation} />// </View>// )// }
// //Styling Browse Restaurant Data// const styles = StyleSheet.create({// container: {// flex: 1// },// restaurantRowStyle: {// flex: 1,// flexDirection: "row",// padding: 20, height: "10%"// },// restaurantHeading: {// flexDirection: "row"// },// restaurantImage: {// height: "130%",// width: "100%",// borderRadius: 5// },// restaurantText: {// marginLeft: 10,// fontSize: 16// },// rightArrow: {// height: 12,// width: 12,// marginTop: 20,// },// gpsIcon: {// height: 20,// width: 20,// },// locationText: {// color: '#A9A9A9'// },// heartIcon: {// height: 18,// width: 18,// marginLeft: 10// },// liketext: {// color: '#A9A9A9'// }// });
// export default BrowseRestaurants;

//BrowseCategories.js
import React, { useState, useEffect } from "react";import { Text, View, StyleSheet, Image, ScrollView, TouchableOpacity } from "react-native";import Header from "./Header";import Footer from "./Footer";import Axios from 'axios';
//Browse Categories Pageconst BrowseCategories = ({ navigation }) => {
 const [allCategory, setAllCategory] = useState([]);
 useEffect(() => { Axios.get('https://damp-sea-94376.herokuapp.com/api/getCategories') .then(function (response) { //alert(JSON.stringify(response.data.data)); setAllCategory(response.data.data); }) .catch(function (error) { alert(error.message); }) }, []);
 return ( <View style={styles.container}> <Header heading="Browse Categories" navigationProp={navigation} navigationRoute={'Login'} /> <ScrollView>
 <View style={styles.browseCategoryRowFlex}> {allCategory.map((item) => { return ( <View>
 <View style={styles.columnViewStyle}> <TouchableOpacity onPress={() => navigation.navigate('BrowseRestaurant', { categoryName: item.category })}> {item.category === "restaurants" && <Image style={styles.browseImageIcon} source={require('../assets/restaurant-icon.png')} /> }
 {item.category === "hotels" && <Image style={styles.browseImageIcon} source={require('../assets/hotel-icon.jpg')} /> }
 {item.category === "nightlife" && <Image style={styles.browseImageIcon} source={require('../assets/nightlife-icon.jpg')} /> }
 {item.category === "shopping" && <Image style={styles.browseImageIcon} source={require('../assets/shopping-icon.png')} /> }
 {item.category === "culture" && <Image style={styles.browseImageIcon} source={require('../assets/culture-icon.png')} /> }
 {item.category === "popular" && <Image style={styles.browseImageIcon} source={require('../assets/heart-icon-blue.png')} /> }
 <Text style={styles.categoriesText}>{item.category}</Text> </TouchableOpacity> </View>
 </View> ) } )}
 </View>
 </ScrollView> <Footer props={navigation} /> </View> )}
//Styling Browse Categories Pageconst styles = StyleSheet.create({ container: { flex: 1, justifyContent: "center", alignItems: "center" }, browseCategoryRowFlex: { flexDirection: "row", flexWrap: "wrap", alignItems: "flex-start", //paddingHorizontal: 20, paddingVertical: 20, //marginTop: 20, justifyContent: "center", marginBottom: 40 }, columnViewStyle: { width: "90%", height: "30%", //height: "120%", backgroundColor: "#FDFEFE", paddingVertical: 10, paddingHorizontal: 30, //marginLeft: 10, textAlign: "center", flexDirection: "column", justifyContent: "center", alignItems: "center", borderWidth: 1, borderColor: "#D3D3D3", borderRadius: 5, marginTop: 10, //marginBottom: 20 }, browseImageIcon: { width: 80, height: 80, }, categoriesText: { textAlign: "center", marginTop: 5, fontSize: 15, textTransform: "capitalize" }});
export default BrowseCategories;


// import React from "react";// import { Text, View, StyleSheet, Image, ScrollView, TouchableOpacity } from "react-native";// import Header from "./Header";// import Footer from "./Footer";
// const getDataUsingSimpleGetCall = () => {// axios// .get('https://damp-sea-94376.herokuapp.com/api/getCategories')// .then(function (response) {// alert(JSON.stringify(response.data));// })// .catch(function (error) {// alert(error.message);// })// };

// //Browse Categories Page// const BrowseCategories = ({navigation}) => {// return (// <View style={styles.container}>// <Header heading="Browse Categories" />// <ScrollView>// <View style={styles.browseCategoryRowFlex}>// <View style={styles.columnViewStyle}>// <TouchableOpacity onPress={() => navigation.navigate('BrowseRestaurant') }>// <Image style={styles.browseImageIcon} source={require('../assets/restaurant-icon.png')} />// <Text style={styles.categoriesText}>Restaurants</Text>// </TouchableOpacity>// </View>// <View style={styles.columnViewStyle}>// <TouchableOpacity>// <Image style={styles.browseImageIcon} source={require('../assets/hotel-icon.jpg')} />// <Text style={styles.categoriesText}>Hotels</Text>// </TouchableOpacity>// </View>// </View>
// <View style={styles.browseCategoryRowFlex}>// <View style={styles.columnViewStyle}>// <TouchableOpacity>// <Image style={styles.browseImageIcon} source={require('../assets/nightlife-icon.jpg')} />// <Text style={styles.categoriesText}>Nightlife</Text>// </TouchableOpacity>
// </View>// <View style={styles.columnViewStyle}>// <TouchableOpacity>// <Image style={styles.browseImageIcon} source={require('../assets/shopping-icon.png')} />// <Text style={styles.categoriesText}>Shopping</Text>// </TouchableOpacity>// </View>// </View>
// <View style={styles.browseCategoryRowFlex}>// <View style={styles.columnViewStyle}>// <TouchableOpacity>// <Image style={styles.browseImageIcon} source={require('../assets/culture-icon.png')} />// <Text style={styles.categoriesText}>Culture</Text>// </TouchableOpacity>// </View>// <View style={styles.columnViewStyle}>// <TouchableOpacity>// <Image style={styles.browseImageIcon} source={require('../assets/heart-icon-blue.png')} />// <Text style={styles.categoriesText}>Popular</Text>// </TouchableOpacity>// </View>
// </View>
// </ScrollView>// <Footer props={navigation}/>// </View>// )// }
// //Styling Browse Categories Page// const styles = StyleSheet.create({// container: {// flex: 1,// justifyContent: "center",// alignItems: "center"// },// browseCategoryRowFlex:// {// flexDirection: "row",// paddingHorizontal: 40,// marginTop: 20,// justifyContent: "center",// },// columnViewStyle: {// width: "50%",// //height: "120%",// backgroundColor: "#FDFEFE",// paddingVertical: 20,// marginLeft: 10,// textAlign: "center",// flexDirection: "column",// justifyContent: "center",// alignItems: "center",// borderWidth: 1,// borderColor: "#D3D3D3",// borderRadius: 5,// },// browseImageIcon: {// width: 80,// height: 80,// },// categoriesText: {// textAlign: "center",// marginTop: 5,// fontSize: 15// }// });
// export default BrowseCategories;

//routes/AppRoutes.js
import { createStackNavigator } from 'react-navigation-stack';import { createAppContainer } from 'react-navigation';
import Home from '../src/Home';import Login from '../src/Login';import BrowseRestaurant from '../src/BrowseRestaurant';import BrowseCategories from '../src/BrowseCategories';
//Creating react navigation for the appconst Navigator = createStackNavigator( { Home: Home, Login: Login, BrowseRestaurant: BrowseRestaurant, BrowseCategories: BrowseCategories, }, { initialRouteName: 'Home', headerMode:false, });
const AppRoute = createAppContainer(Navigator);
export default AppRoute;

//App.js
//************************************APP.JS*****************************************************//
import React from 'react';import AppRoute from './routes/AppRoutes';//import { View, Text } from "react-native";
const App = () => { return ( //Routes for the pages of app <AppRoute /> // <View style={{justifyContent: 'center', alignItems: 'center', flex: 1}}> // <Text>Hello World</Text> // </View> )}export default App;
//********************************Fetching data from API**************************************//
// import React, { useState } from 'react';// import {StyleSheet, View, TouchableOpacity, Text} from 'react-native';// import Axios from 'axios';
// const App = () => {
// const [userData, setUserData] = useState([]);
// // const getDataUsingSimpleGetCall = () => {// Axios// .get('https://jsonplaceholder.typicode.com/todos/1')// .then(function (response) {// //alert(JSON.stringify(response.data));// setUserData(response.data);// })// .catch(function (error) {// alert(error.message);// })// // };// return (// <View style={styles.container}>// <Text>Hello World</Text>// <Text>{userData.title}</Text>// {/* <TouchableOpacity// style={styles.buttonStyle}// onPress={getDataUsingSimpleGetCall}>// <Text>Get Call</Text>// </TouchableOpacity> */}// </View>// );// };
// const styles = StyleSheet.create({// container: {// justifyContent: 'center',// flex: 1,// padding: 16,// },// buttonStyle: {// alignItems: 'center',// backgroundColor: '#DDDDDD',// padding: 10,// width: '100%',// marginTop: 16,// },// });
// export default App;
//***********************************Browse Categories*******************************************//
// import React from "react";// import { Text, View, StyleSheet, Image, ScrollView, TouchableOpacity } from "react-native";// import Header from "./src/Header";// import Footer from "./src/Footer";
// const App = ({ navigation }) => {// return (// <View style={styles.container}>// <Header heading="Browse Categories" />// <ScrollView>
// <View style={styles.browseCategoryRowFlex}>// <View style={styles.columnViewStyle}>// <TouchableOpacity onPress={() => navigation.navigate('BrowseRestaurants')}>// <Image style={styles.browseImageIcon} source={require('./assets/restaurant-icon.png')} />// <Text style={styles.categoriesText}>Restaurants</Text>// </TouchableOpacity>// </View>// <View style={styles.columnViewStyle}>// <TouchableOpacity>// <Image style={styles.browseImageIcon} source={require('./assets/hotel-icon.jpg')} />// <Text style={styles.categoriesText}>Hotels</Text>// </TouchableOpacity>// </View>// </View>
// <View style={styles.browseCategoryRowFlex}>// <View style={styles.columnViewStyle}>// <TouchableOpacity>// <Image style={styles.browseImageIcon} source={require('./assets/nightlife-icon.jpg')} />// <Text style={styles.categoriesText}>Nightlife</Text>// </TouchableOpacity>
// </View>// <View style={styles.columnViewStyle}>// <TouchableOpacity>// <Image style={styles.browseImageIcon} source={require('./assets/shopping-icon.png')} />// <Text style={styles.categoriesText}>Shopping</Text>// </TouchableOpacity>// </View>// </View>
// <View style={styles.browseCategoryRowFlex}>// <View style={styles.columnViewStyle}>// <TouchableOpacity>// <Image style={styles.browseImageIcon} source={require('./assets/culture-icon.png')} />// <Text style={styles.categoriesText}>Culture</Text>// </TouchableOpacity>// </View>// <View style={styles.columnViewStyle}>// <TouchableOpacity>// <Image style={styles.browseImageIcon} source={require('./assets/heart-icon-blue.png')} />// <Text style={styles.categoriesText}>Popular</Text>// </TouchableOpacity>
// </View>// </View>
// </ScrollView>// <Footer />// </View>// )// }
// const styles = StyleSheet.create({// container: {// flex: 1,// justifyContent: "center",// alignItems: "center"// },// browseCategoryRowFlex:// {// flexDirection: "row",// paddingHorizontal: 40,// marginTop: 20,// justifyContent: "center",// },// columnViewStyle: {// width: "50%",// //height: "120%",// backgroundColor: "#FDFEFE",// paddingVertical: 20,// marginLeft: 10,// textAlign: "center",// flexDirection: "column",// justifyContent: "center",// alignItems: "center",// borderWidth: 1,// borderColor: "#D3D3D3",// borderRadius: 5,// },// browseImageIcon: {// width: 80,// height: 80,// },// categoriesText: {// textAlign: "center",// marginTop: 5,// fontSize: 15// }// });
// export default App;
//*********************************************Browse Restaurants*******************************//
// import React from "react";// import { Text, View, StyleSheet, Image, ScrollView, TouchableOpacity } from "react-native";// import Footer from "./src/Footer";// import Header from "./src/Header";
// const datas = [// {// id: 1,// restaurantImageSource: require('./assets/pizza.jpg'),// restaurantName: "Gramercy Tavern",// gpsSource: require('./assets/location.jpg'),// locationName: "42 E 20th St",// heartIconSource: require('./assets/heart.jpeg'),// likesText: "228",// rightArrowSource: require('./assets/right-arrow.jpeg')// },// {// id: 2,// restaurantImageSource: require('./assets/burger.jpg'),// restaurantName: "Blue Hill",// gpsSource: require('./assets/location.jpg'),// locationName: "75 Washington PI",// heartIconSource: require('./assets/heart.jpeg'),// likesText: "215",// rightArrowSource: require('./assets/right-arrow.jpeg')// },// {// id: 3,// restaurantImageSource: require('./assets/pasta.png'),// restaurantName: "Le Bernardin",// gpsSource: require('./assets/location.jpg'),// locationName: "155 W 51st St",// heartIconSource: require('./assets/heart.jpeg'),// likesText: "199",// rightArrowSource: require('./assets/right-arrow.jpeg')// },// {// id: 4,// restaurantImageSource: require('./assets/french-fries.jpg'),// restaurantName: "Jean-Georges",// gpsSource: require('./assets/location.jpg'),// locationName: "1 Central Park West",// heartIconSource: require('./assets/heart.jpeg'),// likesText: "183",// rightArrowSource: require('./assets/right-arrow.jpeg')// },// {// id: 5,// restaurantImageSource: require('./assets/brownie.jpg'),// restaurantName: "The Four Seasons",// gpsSource: require('./assets/location.jpg'),// locationName: "99 E 52md St",// heartIconSource: require('./assets/heart.jpeg'),// likesText: "178",// rightArrowSource: require('./assets/right-arrow.jpeg')// },// {// id: 6,// restaurantImageSource: require('./assets/sandwich.jpeg'),// restaurantName: "Ninja New York",// gpsSource: require('./assets/location.jpg'),// locationName: "25 Hudson St",// heartIconSource: require('./assets/heart.jpeg'),// likesText: "78",// rightArrowSource: require('./assets/right-arrow.jpeg')// },// ];
// function createData(data) {// return (// <View>// <View style={styles.restaurantRowStyle}>
// <View style={{ width: "20%" }}>// <Image style={styles.restaurantImage} source={data.restaurantImageSource} />// </View>
// <View style={{ width: "70%", marginTop: 5 }}>// <Text style={styles.restaurantText}>{data.restaurantName}</Text>// <View style={{ flexDirection: "column" }}>// <View style={{ flexDirection: "row", marginLeft: 5, marginTop: 5 }}>// <Image style={styles.gpsIcon} source={data.gpsSource} />// <Text style={styles.locationText}>{data.locationName}</Text>// <Image style={styles.heartIcon} source={data.heartIconSource} ></Image>// <Text style={styles.liketext}>{data.likesText}</Text>// </View>// </View>// </View>
// <View style={{ width: "10%" }}>// <Image style={styles.rightArrow} source={data.rightArrowSource}></Image>// </View>
// </View>
// <View// style={{// borderBottomColor: '#A9A9A9',// borderBottomWidth: 0.4,// marginTop: 5// }}// />// </View>// )// }
// const App = () => {// return (
// <View style={styles.container}>// <Header heading="Browse Restaurants"/>// <ScrollView>// {datas.map(createData)}// </ScrollView>// <Footer />// </View>// )// }
// const styles = StyleSheet.create({// container: {// flex: 1// },// restaurantRowStyle: {// flex: 1,// flexDirection: "row",// padding: 20, height: "10%"// },// restaurantHeading: {// flexDirection: "row"// },// restaurantImage: {// height: "130%",// width: "100%",// borderRadius: 5// },// restaurantText: {// marginLeft: 10,// fontSize: 16// },// rightArrow: {// height: 12,// width: 12,// marginTop: 20,// },// gpsIcon: {// height: 20,// width: 20,// },// locationText: {// color: '#A9A9A9'// },// heartIcon: {// height: 18,// width: 18,// marginLeft: 10// },// liketext: {// color: '#A9A9A9'// }// });
// export default App;
